import { ChangeDetectorRef } from '@angular/core';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-motivational',
  templateUrl: './motivational.component.html',
  styleUrls: ['./motivational.component.css']
})
export class MotivationalComponent implements OnInit {

  moQuote : string = "";
  randomNumber: number = 0;
  constructor(private _ref: ChangeDetectorRef) { }

  ngOnInit() {
    const setInterval = window['__zone_symbol__setInterval'];
    setInterval(() => {
      this.randomNumber = Math.floor(Math.random() * (161 - 1) + 1) ; 
      this.moQuote = this.moArray[this.randomNumber].toUpperCase();
      this._ref.detectChanges();
    },60000);
    
  }

  moArray : Array<String> = [
    "Take every chance in your life because some things happen only once.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Before going to sleep every night forgive everyone and sleep with a clean heart.",
    "You only live once, but if you do it right, once is enough.  -Mae West",
    "3 Accessories to wear today: Smile, Confidence and Positive energy.",
    "The limit is not in the sky. The limit is in the mind.",
    "Courage is resistance to fear, mastery of fear,not absence of fear. - Mark Twain",
    "Push yourself beacuse no one else is going to do it for you.",
    "Make Mistakes you're Human not a Robot.",
    "Begineers are many, Finishers are few.",
    "When we fell love and kindness toward others, It not only makes others feel loved and cared for, but it helps us also to develop inner happiness and peace. - Dalai Lama",
    "Mistakes happen by situations, not by intention. So, always try to know the reason behind. Every mistake of our loved ones. That is the Way to Value a Relation.",
    "Win life by avoiding two things in life. Comparing with others and Expecting from others.",
    "You've only got three choices in life : Give up, Give in or Give it all you've got.",
    "Crying releases extra stress hormones, which is why you feel Better after doing so.",
    "There are 2 types of pain in this world. PAIN that hurts you. PAIN that changes you.",
    "Whenever you feel sad/alone just remember that there are billion of cells in your body and all they care about is you.",
    "The world is full of nice people. If you can't find one, BE ONE.",
    "When nails grow long, we cut nails not fingers. Similarly when  misunderstanding grow up, cut your ego, not your relationship.",
    "No one in this world is rich enough to buy his own childhood and youth back. Only friends help to recreate those moments from time to time at no cost.",
    "Make peace with your past so it won't spoil the present.",
    "Don't take yourself so seriously. No one else does.",
    "Dont't waste your precious energy on gossip,energy vampires,issues of the past,negative thoughts or things you cannot control. Instead invest your energy in the positive present moment.",
    "Don't let the darkness of the past cover the brightness of the future.",
    "Don't complain about your life when you are the one who is handling it.",
    "Your future begins with your next thought.",
    "People will appreciate results. The process is yours to enjoy.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Start each day with a positive thought.",
    "Life's a game where money is your score and books are the cheatcodes.",
    "People know you for what you've done, not for what you plan to do.",
    "The difference between who you are and what you want to be is what you do.",
    "Stop doubting YOURSELF. Work Hard and make it Happen.",
    "Life is a circle of Happiness, Sadness, Hard Times and Good Times. If you're going through a hard time, know that Good Times are on the way.",
    "The most valuable real estate is the space you occupy in other people's heart.",
    "A dream doesn't come true automatically. It demands firm determination, hard work & commitment.",
    "The times in life, that seems to be worst, always turn out for the best.",
    "The thing always happens that you really believe in;and the belief in a thing makes it happen.",
    "Great things come to those who hustle.",
    "A person who feels appreciated will always do more than is expected.",
    "Ask yourself if what you're doing today is getting you closer to where you want to be tomorrow.",
    "People with the worst past create the best future.",
    "Life is 10% what happens to me and 90% of how i react to it.",
    "Take Risks in your life. If You Win, You Can Lead. If You Loose, You Can Guide. - Swami Vivekananda.",
    "Feel the fear and do it anyway.",
    "Don't let yourself be controlled by three things: People, Money and Past Experiences.",
    "Stay calm. Be strong. Never let anyone destroy you.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "Believe you deserve it and the universe will serve it.",
    "Life is a journey from the consequences of our actions, to the regrets of our inactions.",
    "If the plan doesn't work, change the plan but never the goal.",
    "Be stubborn about your goals, but flexible about your methods.",
    "Failure defeats Losers, Failure inspires Winners.",
    "Have patience. Everything is difficult before it is easy.",
    "All you need to change is WILL.",
    "Act like you trust people, but do not. You never know who is using you.",
    "Positive Mind,Positive Vibes,Positive Life.",
    "Success is where Preparation and Opportunity meet.",
    "Happiness is not a destination it is a way of life.",
    "Good things come to thos who work their asses off and never give up.",
    "Pain is temporary. Glory is forever.",
    "Eventually you'll end up where you need to be, with who you're meant to be with, and doing what you should be doing.Patience is the key.",
    "Be willing to sacrifice what you are for what you will become.",
    "I want to see what happens if i don't give up.",
    "Let's not allow our fears to fulfill our future.",
    "Don't give up just because things are hard.",
    "You are capable of AMAZING things.",
    "Faith makes things possible, not easy.",
    "There is nothing to fear because i can not fail. Only learn,grow and become better than i have ever been before.",
    "What you tell yourself everyday will either lift you up or tear you down.",
    "One cannot be present if they are looking backward.",
    "When people believe in you, it gives you courage and motivation, but when you believe in yourself, it gives you persistence, determination and infinite energy. THINK BIG & POSITIVE.",
    "People will hate you, rate you, shake you, and break you. But how strong you stand is what makes you.",
    "Life is not a struggle. It is your attachment to your desires that makes life a struggle.",
    "Old habits won't bring new results.",
    "Change your vision to change your life.",
    "Pain is temporary but giving up is forever.",
    "I can accept failure. Everyone fails at something. But i cannot accept not trying.",
    "Opportunity dances with those who are already on the dance floor.",
    "Don't let the darkness of the past cover the brightness of the future.",
    "Trying and DOing are two different things. When you try, you hope. When you do, you succeed.",
    "If there is no vision, there is no hope.",
    "Underestimate no one especially yourself.",
    "In 10 years, be able to say 'I MADE IT'",
    "Willingness to take risk is the path to success.",
    "Money is simply the outcome of your FOCUS,ENERGY and TIME.",
    "Risk is the down payment for SUCCESS.",
    "Life is about three things: Winning others heart,Losing bad things & Sharing happy moments.",
    "If it is important enough to you, you will find a way. If it is not, you will find an excuse.",
    "Never assume that loud is strong and quiet is weak.",
    "It's gonna get harder before it gets easier. But it will get better, you just gotta make it through the hard stuff first.",
    "Forget the mistakes, Remember the lessons.",
    "Tough times make you strong, Hard learned lessons make you wise.",
    "All you need in this life is ignorance and confidence, and then success is sure.",
    "The past cannot be changed. The future is yet in your power.",
    "Never be the prisoner of your past, but the architect of your future.",
    "Caring less is the easiest way to be Happy.",
    "When you do all you CAN do, God will do what you CANNOT do.",
    "A negative mind will never give you a positive life.",
    "Take every chance, Drop every fear.",
    "The bad news is time flies, the good news is you're the pilot.",
    "He Believed he could so he did.",
    "Think of the consequences if you do nothing.",
    "When life gets blurry adjust your focus.",
    "What screws us up most in life is the picture in our head of how it is supposed to be.",
    "I can I will I must",
    "Invest in yourself to the point that it makes someone else want to invest in you.",
    "You get paid for your value, not your time.",
    "Your coffe jumpstarts your brain. Find what jumpstarts your soul and do that every morning. You deserve it.",
    "Never take a day for granted.",
    "Create a way not an excuse.",
    "Change your vision to change your life.",
    "Life is all about 3 things : Wining others heart, Losing bad things & Sharing happy moments.",
    "Your fate have just two palms. But your hardwork have two arms.",
    "The fears you dont face become your limits.",
    "You dont have to be great to start, but you have to start to be great.",
    "For every wish fulfilled, our parents have sacrificed their needs.",
    "Grind in your 20's; Build in your 30's; Chill in your 40's",
    "You become what you think so think positive.",
    "Take your time to love the journey.",
    "Success is achieved by developing our strengths, not by eliminating our weakness.",
    "Rich is not a goal. Five million in three years is.",
    "Honest relations are just like water, no color, no shape, no place, no taste but still very important for life.",
    "Your dream doesn't have an expiration date. Take a deep breath and try again.",
    "Maybe it's time to turn the page.",
    "Two things prevent us from happiness; Living in the past and observing others.",
    "It's faith in something and enthusiasm for something that makes a life worth living.",
    "Never expect a certain outcome. But always expect the best outcome.",
    "Control over emtions, that is all you need.",
    "Don't wait to be rich to be happy. Happiness is free.",
    "Motivation gets you started and habit keeps you going.",
    "The secret of success is to know something nobody else knows.",
    "Never feed your fears.",
    "You don't need everything to enjoy life. You already have life to enjoy everything.",
    "If you don't go after what you want, you will never have it.",
    "Always remember your focus determines your reality.",
    "The problem is, you think you have time.",
    "Controlling your choices more tthan anything else will determine your destiny.",
    "Never quit. If you stumble get back up.",
    "Never depend on anyone but yourself.",
    "Be who you want to be.",
    "Great things come to those who hustle.",
    "Never get so busy making a living that you forget to make a life.",
    "Your life won't give you what you want, it'll give you what you worked for.",
    "Your worst battle is between what you know and what you feel.",
    "Everything is temporary; emotions, thoughts, people and scenery. Do not become attached, just flow with it.",
    "Dont give in to fear. Face tough issues head-on. But do it with optimism and hope, not despair, disaster, and catastrophizing.",
    "Fear defeats more people than any other one thing in the world.We suffer more in imagination than in reality.",
    "Most of your emotions, positive or negative, are determined by how you talk to yourself on a minute-to-minute basis.",
    "It is not what happens to you but the way that you interpret the things that are happening to you that determines how you feel  -Brian Tracy",
    "Dont run away from difficulties and challenges, they are part of success journey and make u stronger.",
    "A well balanced life have all 3- LEARN - be a life time student;EARN - Ethically,adding maximum value;RETURN- contribute your time and money for others benefits",
    "If you don't like something change it. If you can't change it, change your attitude about it. Don't Complain.",
    "Life has no limitations, except the ones you make.",
    "Joy is not in things; it is in us",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope or confidence.",
    "Think, think and think before u make a decision and once u make a decision then get fully committed to it till u achieve your goals.",
    "Every moment is a fresh beginning",
    "Aspire to inspire before we expire",
    "Have enough courage to start and enough heart to finish",
    "The first to apologize is always the bravest. The first to forgive is the strongest. The first to forget is the happiest."
  ]
}
