import { ChangeDetectorRef } from '@angular/core';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-knowledge',
  templateUrl: './knowledge.component.html',
  styleUrls: ['./knowledge.component.css']
})
export class KnowledgeComponent implements OnInit {

  knowQuote : string = "";
  randomNumber: number = 0;

  constructor(private _ref: ChangeDetectorRef) { }

  ngOnInit() {
    const setInterval = window['__zone_symbol__setInterval'];
    setInterval(() => {
      this.randomNumber = Math.floor(Math.random() * (249 - 1) + 1) ; 
      this.knowQuote = this.knowArray[this.randomNumber];
      this._ref.detectChanges();
    },60000);
  }

knowArray : Array<string> = [
  "NOIDA - New Okhla Industrial Development Authority",
  "STD - Subscriber trunk dialing",
  "CHESS - Chariot,Horse,Elephant,Soldiers",
  "KFC - Kentucky Fried Chicken",
  "Nokia - mobile company named based on river name",
  "PAPER - Past And Present Events Report",
  "COLD - Chronic Obstructive Lung Disease",
  "DATE - Date and Time Evolution",
  "EAT - Energy and Taste",
  "JOKE - Joy of Kids Entertainment",
  "PEN - Power Enriched in Nib",
  "SMILE - Sweet Memories in Lips Expression",
  "BYE - Be with You Everytime",
  "AIM - Ambition In Mind",
  "TEA - Taste and Energy admitted",
  "IFSC - Indian Financial System Code",
  "ATM -Automated Teller Machine",
  "POA - Power of Attorney",
  "NOC - Non Objection Certificate",
  "ISI - Indian Standard Institute",
  "UIDAI - Unique Identification Authority of India",
  "PSK - Passport Seva Kendra",
  "USP - Unique Selling Proposition",
  "CC/Bcc - Carbon copy/Blind carbon copy",
  "MICR - Magnetic Ink Character Recognition",
  "MRF - Madras Rubber Factory",
  "WIPRO - Western India Products Limited",
  "HCL - Hindustan Computers limited",
  "AMUL - Anand Milk Union Limited",
  "IBM - International Business Machine",
  "JBL - James Bullough Lansing",
  "PVR - Priya Village Roadshow",
  "LG - Lucky Goldstar",
  "DLF - Delhi Land and Finance",
  "ICICI - Industrial Credit and Investment Corporation of India",
  "AM/PM - Ante meridiem(before noon)/Post Meridiem (after noon)",
  "DELL - Digital Electronic Link Library",
  "HDMI - High-Definition Multimedia Interface",
  "VGA - Video Graphics Array",
  "QVGA - Quarter Video Graphics Array",
  "WVGA - Wide Video Graphics Array",
  "MPEG - Moving Picture Experts Group",
  "IVRS - Interactive Voice Response System",
  "etc - End of thinking Capacity.",
  "OK - Objection Killed",
  "GOOGLE :- Global Organisation Of Oriented Group Language of Earth",
  "APPLE:- Asian Passenger Payload Experiment",
  "HP :- Hewlett-Packard",
  "IBM:- International Business Machines Corporation",
  "HCL:-Hindustan Computer Limited",
  "WIPRO:- Western India Product Limited",
  "GE:-General Electronics",
  "INFOSYS:-Information System",
  "AOL:- American Online",
  "BPL:- British Process Laboratory",
  "INTEL:- Integrated Electronics",
  "CISCO:- Computer Information System Company",
  "DELL:- michael DELL",
  "SONY:-Sound Of New York",
  "AMD:- Advance micro devices",
  "LENOVO:- LE(Legend),NOVO(New)",
  "COMPAQ:- Compatibility And Quality",
  "Old name of Japan - NIPPON",
  "National sport of china - TABLE TENNIS",
  "Animal breathes through its skin - EARTHWORMS",
  "Father of Pen Drive - DOV MORAN an Israeli entrepreneur ",
  "City known as Manchester of India - AHMEDABAD",
  "CIty Known as White city of India - UDAIPUR",
  "City of love in World - PARIS",
  "City known as Queen of Hills - MUSSOORIE",
  "City Known as city of seven islands - MUMBAI",
  "Gautam Buddha's Name in Childhood - SIDDHARTHA", 
  "Meaning of Deepavali - Row of lights",
  "Architects of Indus valley Civilization - DRAVIDANS",
  "Modern name for Pataliputra - PATNA",
  "Name of Bhai Dhooj in state of west Bengal - BHAI PHONTA",
  "Instruments used to measure Atmospheric Pressure - BAROMETER",
  "Designed Indian Parliament Building - HERBERT BEKAR",
  "Country called as constitution research society - GREECE",
  "Who gave the slogan of 'Inquilab Zindabad' - HASRAT MOHANI",
  "Country with most amount of time zones - FRANCE ( 12 time zones )",
  "Designer of indian flag - PINGALI VENKAYYA",
  "City of India called as Zero-mile center - NAGPUR",
  "Where the sun rises first in india - ARUNACHAL PRADESH",
  "What is it that we buy to drink but do not drink - GLASS",
  "World hindi day - 10th January",
  "Indian Army day - 15th January",
  "Martyrs Day - 30th January",
  "World Radio Day - 13th February",
  "International Mother Language Day - 21st February",
  "Hindi day - 14th September",
  "Known as Napoleon of India - SAMUDRAGUPTA",
  "Largest Indian producer of diamonds - MADHYA PRADESH",
  "India's first Indigenously built submarine - INS SHALKI(S46)",
  "Which bird can fly backward – HUMMINGBIRDS",
  "Which bird cannot fly – OSTRICH",
  "Naval Ship Somudra Joy arrives at Visakhapatnam on a goodwill visit - BANGLADESH",
  "Fist Talkie film of India - ALAM ARA ( Ardeshir Irani released alam ara the first indian talkie on 14th March 1931)",
  "Name of countries whose national anthem has only music but no words - SPAIN, SAN MARINO, KOSOVO, BOSNIA AND HERZEGOVINA, BAHRAIN",
  "Diwali is celebrated and referred to as 'Tihar'/'Swanti' - NEPAL",
  "Shortest complete sentence in the English language – GO",
  "Fairy queen is the oldest working indian Locomotive - queen works with stram engine,build in 1855 and retrired in 1909 and restore in 18th july 1997 and travels with maximum speed by 40 kmph.",
  "Apart from India , South Korea celebrates independence day on 15th August",
  "Emergency was declared in India on 25th June 1975.",
  "Epidemic spreads quickly in one region & pandemic speads quickly worldwide",
  "Tomatoes originally called as Love Apple",
  "Gandhiji was given title of Mahatma by Ravindranath Tagore",
  "IF president of india wishes to resign where does he submit his resignation letter - Vice president of India",
  "Alexander the great visited india in 326 BC.",
  "First day of diwali season is called Dhanteras",
  "Diwali is celebrated in Malaysia in the name of Hari Diwali",
  "Karnataka is the largest producer of coffee in India followed by Kerala and Tamil Nadu",
  "Nilgiri expresss is slowest moving train in india with an average speed of 10 kmph.",
  "Bholu or bholu the guard elephant is mascot of indian railway designed by national institute of design and was unveiled on 16th April 2002.",
  "Eunoia at six letters long, is the shortest word in the English language that contains all five main vowels. Eunoia is the goodwill a speaker cultivates between himself and his audience. It comes from the Greek word.",
  "Sir Tim Berners-Lee – Founder of World Wide Web",
  "Vint Cerf And Bob Kahn – Founder of TCP/IP",
  "Larry Page and Sergey Brin – Founder of Google Inc.",
  "David Filo and Jerry Yang – Founder of Yahoo! Inc.",
  "Steven Paul Jobs – Founder of Apple Inc.",
  "Mark Zuckerberg – Founder of Facebook",
  "Chad Hurley and Steve Chen – Founder of YouTube",
  "Linus Torvalds – Founder of Linux",
  "Jack Dorsey – Founder of Twitter",
  "Kevin Rose – Founder of Digg",
  "Bram Cohen – Founder of BitTorrent",
  "Mike Morhaime – Founder of Blizzard Entertainment",
  "Jimmy Wales – Founder of Wikipedia",
  "Jeff Preston Bezos – Founder of Amazon",
  "Shawn Fanning – Founder of Napster, Rupture",
  "Pierre Omidyar – Founder of eBay",
  "Jack Ma – Founder of Alibaba",
  "Craig Newmark – Founder of Craigslist",
  "Matt Mullenweg – Founder of WordPress",
  "Thomas Anderson – Founder of MySpace",
  "Garrett Camp – Founder of StumbleUpon",
  "Jon Postel – Founder of Internet Pioneer",
  "Caterina Fake – Founder of Flickr",
  "Marc Andreessen – Founder of NETSCAPE",
  "New Delhi to bhopal shatabdi express is fastest running train in india. Runs at a top speed of 150 kmph on delhi - agra stretch and at an average speed of 91 kmph.",
  "The Volkswagen Group owns Bentley,Bugatti,Lamborghini,Audi,Ducati,SEAT and Skoda",
  "Famous 4 rings logo of Audi represent the 4 Companies which started Audi in 1932: DKW,Horch,Wanderer and Audi",
  "Largest state(Area wise) - RAJASTHAN",
  "India's First President - DR. RAJENDRA PRASAD",
  "First Prime Minister - JAWAHAR LAL NEHRU",
  "First Women Prime Minister - INDIRA GANDHI",
  "Silicon Valley of India - BANGALORE",
  "Financial Capital of India - MUMBAI",
  "Iron Man of India - Sardar Vallabhai Patel",
  "Guru dev - Rabindranath Tagaore",
  "Nightingale of India - Sarojini Naidu",
  "Lokmanya - Bal Gangadhar Tilak",
  "Lal,Bal,Pal - Lala Lajpat Rai, Bal Gangadhar Tilak, Bipin Chandra Pal",
  "National Emblem - Lion Capital of Ashoka at Sarnath",
  "National Flag - Tricolor",
  "National Anthem - Jana Gana Mana",
  "National Song - Vande Mataram",
  "Natinal Animal - Tiger",
  "National Bird - Peacock",
  "Motto - Satyameva Jayate",
  "Number of states - 29 (Telangana youngest state)",
  "Union Territories - 7 including Capital Territory",
  "Major water bodies - Arabian Sea, Bay of Bengal, Indian Ocean",
  "Main agricultural products - Rice,Wheat,Jute,Sugarcane,Cotton,Tea,Coffee",
  "Ballia was independent on 20 August 1942 and it was the first independent city of India.",
  "India has the largest postal network in the world with over 1, 55,015 post offices. A single post office on an average serves a population of 7,175 people. The floating post office in Dal Lake, Srinagar, was inaugurated in August 2011.",
  "Mawsynram, a village on the Khasi Hills, Meghalaya, receives the highest recorded average rainfall in the world. Cherrapunji, also a part of Meghalaya, holds the record for the most rainfall in the calendar year of 1861.",
  "Bandra Worli Sealink has steel wires equal to the earth's circumference",
  "At an altitude of 2,444 meters, the Chail Cricket Ground in Chail, Himachal Pradesh, is the highest in the world. It was built in 1893 and is a part of the Chail Military School.",
  "Shampoo was invented in India, not the commercial liquid ones but the method by use of herbs. The word 'shampoo' itself has been derived from the Sanskrit word champu, which means to massage.",
  "Water on the moon was discovered by India.In September 2009, India's ISRO Chandrayaan- 1 using its Moon Mineralogy Mapper detected water on the moon for the first time.",
  "The father of India's missile programme had visited Switzerland back in 2006. Upon his arrival, Switzerland declared May 26th as Science Day.",
  "The first rocket was so light and small that it was transported on a bicycle to the Thumba Launching Station in Thiruvananthapuram, Kerala.",
  "India was the first country to develop extraction and purifying techniques of sugar. Many visitors from abroad learnt the refining and cultivation of sugar from us.",
  "Shakuntla Devi was given this title after she demonstrated the calculation of two 13 digit numbers: 7,686,369,774,870 × 2,465,099,745,779 which were picked at random. She answered correctly within 28 seconds.",
  "Rabindranath Tagore is credited not only for writing the Indian national anthem, Jana Gana Mana, but the Bangladeshi national anthem, Amar Sonar Bangla, as well. He was also offered knighthood by the British but refused the honour after the Jalianwala Bagh massacre.",
  "After defeating Germany 8-1 in the 1936 Berlin Olympics, Major Dhyan Chand, the wizard of hockey, was summoned by Hitler. He was promised German citizenship, a high post in the German military and the chance to play for the German national side. Dhyan Chand however declined the offer.",
  "Havell's is purely an Indian brand & named after its first owner.Though the company was bought for just 10 lakh Rupees a long time ago and is now a multi-billion electrical goods company, it's an Indian company and is still named after its original owner, Haveli Ram Gupta.",
  "Initially, diamonds were only found in the alluvial deposits in Guntur and Krishna District of the Krishna River Delta. Until diamonds were found in Brazil during the 18th century, India led the world in diamond production.",
  "Snakes and Ladders originated in India.Earlier known as Moksha Patamu, the game was initially invented as a moral lesson about karma to be taught to children. It was later commercialized and has become one of the most popular board games in the world.",
  "The name 'India' is derived from the River Indus, the valleys around which were the home of the early settlers. The Aryan worshippers referred to the river Indus as the Sindhu.",
  "The Persian invaders converted it into Hindu. The name 'Hindustan' combines Sindhu and Hindu and thus refers to the land of the Hindus.",
  "Chess was invented in India. Algebra, Trigonometry and Calculus are studies, which originated in India.",
  "The 'Place Value System' and the 'Decimal System' were developed in India in 100 B.C.",
  "The largest employer in India is the Indian Railways, employing over a million people.",
  "India was one of the richest countries till the time of British rule in the early 17th Century. Christopher Columbus, attracted by India's wealth, had come looking for a sea route to India when he discovered America by mistake.",
  "The value of 'pi' was first calculated by the Indian Mathematician Budhayana, and he explained the concept of what is known as the Pythagorean Theorem. He discovered this in the 6th century, long before the European mathematicians.",
  "The Baily Bridge is the highest bridge in the world. It is located in the Ladakh valley between the Dras and Suru rivers in the Himalayan mountains. It was built by the Indian Army in August 1982.",
  "The four religions born in India - Hinduism, Buddhism, Jainism, and Sikhism, are followed by 25% of the world's population.",
  "There are 300,000 active mosques in India, more than in any other country, including the Muslim world.",
  "Martial Arts were first created in India, and later spread to Asia by Buddhist missionaries.",
  "Yoga has its origins in India and has existed for over 5,000 years.",
  "India’s first ever train ran between Mumbai and Thane.On 16 April 1853, India’s first train commenced its operation.",
  "Mumbai was the first one to start a bus service in India.It was on 15 July 1926, that the first ever bus service in India was started. The first route was ridden between Afghan Church and Crawford Market.",
  "World’s most expensive house is in Mumbai.Antilia, Mukesh Ambani’s 27-story skyscraper is cited as the world’s most expensive house, valued at almost $1 billion. The business tycoon moved into the 400,000 square feet mansion in 2012 with his wife and three children.",
  "When the city was in the hands of the Portuguese, they saw it was a natural water bay. Hence, they called it ‘Bom Bhaia’, which is the Portuguese term for ‘good bay’. Later, Bombay was given to the British as dowry when a Portuguese princess married an English prince. They renamed the city Bombay. And that’s how the city got its name!",
  "Mumbadevi, the patron goddess of the fishing community inspired the name ‘Mumbai’. ‘Mumba’ is the name of the goddess and ‘ai’ is mother. The Mumbadevi temple is situated in Bhuleshwar.",
  "Mumbai has a coastline of about 150 kilometres.Not many people know about its vast coastline. Right from Marine Drive to Aksa Beach, Mumbai has huge coastline. Marine Drive is beautifully embellished with the ‘queen’s necklace’",
  "Rudyard Kipling, the Nobel Laureate who wrote The Jungle Book was born on 30 December 1865 in Mumbai. Kipling's birth home still stands on the campus of the J J School of Art in Bombay which was used as the Dean's residence for many years.",
  "The first person to own a car in India was the great Sir Jamshetji Tata, the founder of the Tata empire. It was in 1901 that any India brought a car.",
  "Human thigh bones are stronger than concrete & The tongue is the strongest muscle in the body.",
  "Cockroaches can live for several weeks with their heads cut off, because their brains are located inside their body. They would eventually die from being unable to eat.",
  "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
  "The elephant is the only mammal that can’t jump!",
  "You are born with 300 bones, but by the time you are an adult you only have 206.",
  "The world's quietest room is located at Microsoft's headquarters in Washington state.",
  "The longest place name on the planet is 85 letters long.People who live in Mamungkukumpurangkuntjunya Hill, Australia, need a little patience when it comes to learning to spell their hometown's name.",
  "The largest cave in the world, Han Son Doong, is in Vietnam.It's over 200 meters high and has its own climate, jungles,rivers and clouds inside.",
  "Steve Jobs named the company 'Apple' because it comes before 'Atari' in a Phone Book. Atari was the company jobs worked before starting apple",
  "Purple is known as a 'Royal' color because it was the hardest dye to extract - it came from sea snails, so only the royalty could afford it.",
  "Our body replaces all it's cell in 7 years, except the Neurons in Brains. You are no longer same as you were in 2015, but memories are the same. Entire body will change many times throughout the life, but memories will remain same. That's why you cannot feel pain of an accident & can feel pain of 20 years old feelings.",
  "Diamond crossing at Nagpur(India). The one place where North,South,East & West Connect.",
  "The Avengers were a real team of Jewish assassins that tracked down and executed Nazi war criminals after WWII.",
  "CAPTCHA stands for Completely Automated Public Turning Test To Test Computers And Humans Apart.",
  "India was never a part of Asia. It separated from Australia and collided with Asia about 55 million years ago. Even today, India is moving North east at the rate of 5 cm per year!",
  "Olympic gold medals are only 1% gold and 92.5% silver.",
  "Music has the ability to repair brain damage as well as return lost memories.",
  "Archie is the first search engine in internet.",
  "To get Night Vision, keep one eye closedd in well lit area and then open it in Darkness. That eye will be able to see in dark. This is why Pirates wear eye patches.",
  "In Rajasthan each and every city is color co-ordinates. Jodhpur is Blue, Jaipur is Pink, Jhalawar is Purple, Udaipur is White.",
  "The first Google Doodle was dedicated to the Burning Man festival attended by Google founders in 1998.",
  "Ambivert is the balance between introvert and extrovert.",
  "ISRO was established by Vikram Sarabhai,a Jain and was taken forward by Dr, APJ Abdul Kalam, a Muslim.Christians donated their church place for building for the first Rocket Launching Station of ISRO. This way ISRO stands as an example of UNIVERSAL RELIGION BROTHERHOOD.",
  "When you walk into a room and you forget why you walked in there in the first place is the phenomenon known as event boundary.",
  "The line that separates the day and night sides on Earth is called Terminator.",
  "Human brain remember more negative memories than positive ones. This is due to the negativity bias the brain sets up as a defense mechanism.",
  "Penguin Olav is a Colonel-In-Chief of the Norwegian King's Guard",
  "The reason why the Wedding Rings is place on the Fourth Finger of your left hand is because it's the only finger that has a vein connecting directly to your heart.",
  "Research found that everyone is able to sing well-it is a learned skill that gets better with practice and worse with disuse.",
  "What's your caste? asked Co-Passenger in a train. I replied 'Software'. He laughed & said, 'You kidding me, what's your fasther caste', I replied 'Electrical'. According to Bhagavad Gita, Chapter 4 Shloka 13 Caste is based on Occupation(work) but not based on Birth.",
  "Nishiyama Onsen Keiunkan, the worlds oldest hotel. Located in Japan, this hotel is 1439 years old and is ran by the same family(52 generations) since inception.",
  "Reindeer are one of the few mammals that can see UV light, allowing them to see lichen(a food source),polar bears against the snow, and urine trails.",
  "MySQL the popular DBMS is named after its co-founder's daughter called 'My'.",
  "Little plastic thing at the end of data cables is called a Ferrite Bead, and it is used to block interference from radio signals from other electronics.",
  "When you transport something by car, it's called a shipment but when yu transport something by ship, it's called Cargo.",
  "Memorizing the lyrics to your favorite songs can help reduce the risk of Alzheimer's and strengthen our brain.",
  "Four dots CMYK(Cyan, Magenta, Yellow and Black) are called registration marks. They are used during printing to help ensure the print is aligned properly. In printing anything these 4 colours are used.",
  "Saffron- Courage & Sacrifice; White - Truth & Purity; Green - Faith, Fertility & Growth; Wheel - Wheel of virtue(Represents motion or growth)",
  "World's longest sea bridge Hong Kong-Zhuhai-Macau bridge with underwater tunnel was inaugurated by President of China Xi Jinping.",
  "Most airplane seats are blue because the colour helps to calm anxiety and relieve fear.",
  "Human brain is 75% water,Blood is 92% water,Bones are 22% water & Muscules are 75% water",
  "World's Tallest Statue is 'Statue of Unity' with a height of 600ft tall(182 m) and cost $430m to build.",
  "India controls the highest battlefield in the world, the Siachen glacier, at 5000 metres above Mean Sea Level.",
  "The most common color for highlighters is yellow because it doesn't leave a shadow on the page when photocopied.",
  "Forgetting is good for the brain: deleting unnecessary information helps the nervous system retain its plasticity.",
  "If you take a nap after learning something new, it can help your retention of it.",
  "There are so many knid of apples that if you ate a new one everyday, it would take over 20 years to try them all."
];
}
